#!/usr/bin/env python3
"""Generate float-only C parameter tables. Development tool; no MCU dependency."""
import argparse
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent


def real(value):
    text = format(float(value or 0), '.10g')
    if '.' not in text and 'e' not in text:
        text += '.0'
    return text + 'f'


def generate(data):
    lines = ['/* SPDX-License-Identifier: BSD-3-Clause */',
             '/* Generated by ../sdk_parameters/generate_c.py; do not edit. */',
             '#include "x5_sdk_parameters.h"', '']

    def table(ctype, name, rows):
        lines.append(f'const {ctype} {name} = {{')
        lines.extend('    ' + row + ',' for row in rows)
        lines.extend(['};', ''])

    def floats(obj, keys):
        return ', '.join(real(obj[k]) for k in keys.split())

    table('x5_sdk_joint_parameters', 'x5_sdk_joints[6]', [
        '{' + floats(j, 'position_min_rad position_max_rad home_rad position_kp '
                     'position_kd position_ki protect_kd sdk_gravity_scale') + '}'
        for j in data['joint_parameters']])
    protocols = {p['sdk_motor_type']: p for p in data['motor_protocols']}
    motors = [(j['can_id'], j['sdk_motor_type'], True, j['feedback_current_threshold'])
              for j in data['joint_parameters']]
    gripper = data['gripper_motor']
    motors.append((gripper['can_id'], gripper['sdk_motor_type'],
                   gripper['current_threshold_checked'], gripper['current_threshold_stored']))
    table('x5_sdk_motor_parameters', 'x5_sdk_motors[7]', [
        '{%d, %d, %d, %d, %du, %s}' % (
            can, typ, 1 if typ == 4 else 0, int(active),
            protocols[typ]['timeout_us'], real(threshold))
        for can, typ, active, threshold in motors])
    table('x5_sdk_protocol_parameters', 'x5_sdk_protocols[2]', [
        '{' + floats(p, 'position_min position_max velocity_min velocity_max '
                     'effort_min effort_max kp_min kp_max kd_min kd_max') + ', '
        + str(p['sdk_motor_type']) + ', {' + ', '.join(map(str, p['quantization_bits']))
        + '}, {' + ', '.join(map(str, p['packed_bits'])) + '}, 8}'
        for p in data['motor_protocols']])
    c = data['controller_parameters']
    table('x5_sdk_control_parameters', 'x5_sdk_control', [
        floats(c, 'integral_limit integral_divisor home_acceleration home_speed '
               'home_position_tolerance home_velocity_tolerance position_acceleration '
               'position_speed interpolation_argument3 interpolation_actual_dt '
               'gripper_home_done_kd'),
        ', '.join(str(c[k]) for k in
                  ['overcurrent_samples', 'gripper_home_samples', 'write_motor_delay_us'])])
    table('float', 'x5_sdk_home_profiles[3][6]', [
        '{' + ', '.join(map(real, data['home_profiles'][k])) + '}'
        for k in ['sdk_default', 'ros1_remote_master', 'ros2_v2_collect']])
    table('x5_sdk_gripper_parameters', 'x5_sdk_gripper_profiles[2]', [
        '{%d, %d, %d, ' % (p['position_limit_active'], p['contact_check_active'],
                           p['contact_samples'] or 0)
        + floats(p, 'position_min_rad position_max_rad kp kd effort_min effort_max '
                 'error_gain position_bias home_velocity home_kd '
                 'contact_feedback_threshold contact_position_offset') + '}'
        for p in data['gripper_profiles']])
    table('x5_sdk_type4_position_parameters', 'x5_sdk_type4_position', [
        floats(data['motor_type4_position'], 'offset feedback_min feedback_max '
               'unwrap_jump_threshold unwrap_span command_wrap_span feedback_recenter_span')])
    table('x5_sdk_urdf_limit_parameters', 'x5_sdk_urdf_limits', [
        floats(data['urdf_limits'], 'position_min_rad position_max_rad effort velocity')])
    for name, key in [('min', 'cartesian_lower'), ('max', 'cartesian_upper')]:
        table('float', f'x5_sdk_cartesian_{name}[6]', [
            ', '.join(map(real, data['binary_constants'][key]['values']))])
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    result = generate(json.loads((HERE / 'parameters.json').read_text()))
    target = HERE.parent / 'c/x5_sdk_parameters.c'
    if args.check:
        if target.read_text() != result:
            raise SystemExit('C parameter tables are stale; run generate_c.py')
        print('C parameter tables match parameters.json')
    else:
        target.write_text(result)


if __name__ == '__main__':
    main()
