#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-2.1-or-later
"""Development-only generator; emitted C constants have no Python dependency."""
import argparse
import math
from pathlib import Path
import sys

PACKAGE = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PACKAGE.parent))
from gravity_compensation import GravityCompensator


def generate():
    lines = ["/* SPDX-License-Identifier: LGPL-2.1-or-later */",
             "/* Generated by generate_model_data.py from the pinned ARX URDFs.",
             " * h_i = m_i*COM_i + mass_of_all_descendants*next_joint_origin.",
             " * Models: 2023, master, 2025. Coordinates: kg*m, link-local.",
             " * Keep -3.1416 exactly as supplied; it is NOT rounded to -pi. */",
             "#ifndef X5_GRAVITY_DATA_H", "#define X5_GRAVITY_DATA_H",
             f"#define X5_FIXED_ROLL_SIN ({math.sin(-3.1416):.17g}f)",
             f"#define X5_FIXED_ROLL_COS ({math.cos(-3.1416):.17g}f)",
             "static const x5_real x5_first_moments[3][6][3] = {"]
    axes = ((0,0,1), (0,1,0), (0,1,0), (0,1,0), (0,0,1), (1,0,0))
    for name in ("2023", "master", "2025"):
        segments = GravityCompensator.from_model(name).segments
        assert len(segments) == 6
        lines.append("    { /* " + name + " */")
        for i, segment in enumerate(segments):
            assert segment.joint_type == "revolute" and segment.axis == axes[i]
            assert segment.rpy == ((-3.1416,0,0) if i in (2,5) else (0,0,0))
            descendants = sum(s.mass for s in segments[i+1:])
            offset = segments[i+1].xyz if i < 5 else (0,0,0)
            h = [segment.mass*segment.com[j] + descendants*offset[j] for j in range(3)]
            lines.append("        {" + ", ".join(f"{v:.17g}f" for v in h) + "},")
        lines.append("    },")
    lines.extend(["};", "#endif", ""])
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    destination = Path(__file__).with_name("x5_gravity_data.h")
    text = generate()
    if args.check:
        if destination.read_text() != text:
            raise SystemExit("generated C constants differ from the pinned URDFs")
        print("C model constants match all three pinned URDFs")
    else:
        destination.write_text(text)
