/* SPDX-License-Identifier: BSD-3-Clause */
/* Generated by ../sdk_parameters/generate_c.py; do not edit. */
#include "x5_sdk_parameters.h"

const x5_sdk_joint_parameters x5_sdk_joints[6] = {
    {-2.618f, 3.14f, 0.0f, 150.0f, 1.0f, 50.0f, 1.0f, 0.8f},
    {-0.1f, 3.6f, 0.0f, 150.0f, 1.0f, 50.0f, 4.0f, 0.8f},
    {-0.1f, 3.0f, 0.0f, 150.0f, 1.0f, 50.0f, 4.0f, 0.8f},
    {-1.57f, 1.57f, 0.0f, 50.0f, 0.8f, 0.0f, 1.0f, 1.32f},
    {-1.57f, 1.57f, 0.0f, 25.0f, 0.8f, 0.0f, 1.0f, 1.32f},
    {-1.97f, 2.08f, 0.0f, 10.0f, 1.0f, 0.0f, 1.0f, 1.32f},
};

const x5_sdk_motor_parameters x5_sdk_motors[7] = {
    {1, 4, 1, 1, 100000u, 13.0f},
    {2, 4, 1, 1, 100000u, 13.0f},
    {4, 4, 1, 1, 100000u, 13.0f},
    {5, 2, 0, 1, 800000u, 13.0f},
    {6, 2, 0, 1, 800000u, 13.0f},
    {7, 2, 0, 1, 800000u, 13.0f},
    {8, 2, 0, 0, 800000u, 13.0f},
};

const x5_sdk_protocol_parameters x5_sdk_protocols[2] = {
    {-12.5f, 12.5f, -45.0f, 45.0f, -10.0f, 10.0f, 0.0f, 500.0f, 0.0f, 5.0f, 2, {16, 12, 12, 12, 12}, {16, 12, 12, 12, 12}, 8},
    {-12.5f, 12.5f, -18.0f, 18.0f, -30.0f, 30.0f, 0.0f, 500.0f, 0.0f, 50.0f, 4, {16, 12, 12, 12, 12}, {16, 12, 12, 9, 12}, 8},
};

const x5_sdk_control_parameters x5_sdk_control = {
    5.0f, 200.0f, 0.08f, 0.2f, 0.08f, 0.1f, 0.5f, 2.0f, 200.0f, 0.02999999933f, 2.0f,
    200, 700, 200,
};

const float x5_sdk_home_profiles[3][6] = {
    {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f},
    {-0.112f, 0.948f, 0.858f, -0.573f, -0.105f, 0.097f},
    {0.0f, 0.948f, 0.858f, -0.573f, 0.0f, 0.0f},
};

const x5_sdk_gripper_parameters x5_sdk_gripper_profiles[2] = {
    {0, 0, 0, 0.0f, 0.0f, 0.0f, 0.2f, -2.0f, 2.0f, 8.0f, -0.1f, -5.0f, 0.2f, 0.0f, 0.0f},
    {1, 1, 51, -3.4f, 0.1f, 2.0f, 0.1f, 0.0f, 0.0f, 0.0f, 0.0f, 2.0f, 0.2f, 1.2f, 0.4f},
};

const x5_sdk_type4_position_parameters x5_sdk_type4_position = {
    0.0f, -13.0f, 13.0f, 12.5f, 25.0f, 6.283185307f,
};

const x5_sdk_urdf_limit_parameters x5_sdk_urdf_limits = {
    -10.0f, 10.0f, 100.0f, 1000.0f,
};

const float x5_sdk_cartesian_min[6] = {
    0.0f, -0.53f, -0.53f, -1.745329252f, -1.483529864f, -1.483529864f,
};

const float x5_sdk_cartesian_max[6] = {
    0.53f, 0.53f, 0.53f, 1.745329252f, 1.483529864f, 1.483529864f,
};
